### ISSUE TITLE
Что если ввести некорректные данные?

### ISSUE THREAD

**Issue by oleg-tgn** [Nikita-Vasilchenko/Labs#5]
одно и главных требований, программа не должна вылетать, а должна выдавать пользователю корректное сообщение при вводе неверных данных
будет ли программа себя вести корректно, если ввести
"1234567890123456789"
"helloworld"
"123.123"

**Comment by Nikita-Vasilchenko** [comment]
Здравствуйте. Я исправил программу , но почему то она не работает! Можете пожалуйста посмотреть в чём ошибка?

**Comment by oleg-tgn** [comment]
смотрю

**Comment by oleg-tgn** [comment]
Вы начали делать проверку метров, при этом еще их не ввели с клавиатуры

**Comment by oleg-tgn** [comment]
```
float meters, inches, arshins;
printf("Meters and inches should be positive \n");
scanf("%f %f", &meters, &inches);

if (meters >= 0 && inches >= 0) {
   // your code
}
```

**Comment by Nikita-Vasilchenko** [comment]
Спасибо вам большое!

**Comment by Nikita-Vasilchenko** [comment]
Здравствуйте. Вы можете посмотреть мою программу. Все ли верно ? Почему то консоль закрывается  автоматически , хотя я написал getchar();

**Comment by oleg-tgn** [comment]
Да я такую особенность тоже заметил на некоторый VS, есть другой вариант как это исправить. Смотрите в книге Полякова

**Comment by Nikita-Vasilchenko** [comment]
Я узнал, что можно использовать несколько getchar();. Я применил два getchar(); и консоль теперь сразу не закрывается. Такой вариант возможен ?
